-- megafunction wizard: %DDR SDRAM Controller v13.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			ddr_ctl_auk_ddr_sdram
-- ============================================================
-- Generated by DDR SDRAM Controller 13.0 [Altera, IP Toolbench 1.3.0 Build 232]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2025 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;
library auk_ddr_lib;

ENTITY ddr_ctl IS
	PORT (
		clk	: IN STD_LOGIC;
		addrcmd_clk	: IN STD_LOGIC;
		write_clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		local_read_req	: IN STD_LOGIC;
		local_write_req	: IN STD_LOGIC;
		local_addr	: IN STD_LOGIC_VECTOR (22 DOWNTO 0);
		local_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		local_ready	: OUT STD_LOGIC;
		local_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_rdata_valid	: OUT STD_LOGIC;
		local_rdvalid_in_n	: OUT STD_LOGIC;
		local_init_done	: OUT STD_LOGIC;
		local_refresh_ack	: OUT STD_LOGIC;
		local_wdata_req	: OUT STD_LOGIC;
		clk_to_sdram	: OUT STD_LOGIC;
		clk_to_sdram_n	: OUT STD_LOGIC;
		ddr_cs_n	: OUT STD_LOGIC;
		ddr_cke	: OUT STD_LOGIC;
		ddr_a	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0);
		ddr_ba	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		ddr_ras_n	: OUT STD_LOGIC;
		ddr_cas_n	: OUT STD_LOGIC;
		ddr_we_n	: OUT STD_LOGIC;
		ddr_dm	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		ddr_dq	: INOUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		ddr_dqs	: INOUT STD_LOGIC_VECTOR (1 DOWNTO 0)
	);
END ddr_ctl;

ARCHITECTURE SYN OF ddr_ctl IS

	SIGNAL signal_wire0	:  STD_LOGIC;
	SIGNAL signal_wire1	:  STD_LOGIC_VECTOR (0 DOWNTO 0);
	SIGNAL signal_wire2	:  STD_LOGIC;
	SIGNAL signal_wire3	:  STD_LOGIC;
	SIGNAL signal_wire4	:  STD_LOGIC;
	SIGNAL signal_wire5	:  STD_LOGIC_VECTOR (2 DOWNTO 0);
	SIGNAL signal_wire6	:  STD_LOGIC_VECTOR (2 DOWNTO 0);
	SIGNAL signal_wire7	:  STD_LOGIC_VECTOR (1 DOWNTO 0);
	SIGNAL signal_wire8	:  STD_LOGIC;
	SIGNAL signal_wire9	:  STD_LOGIC;
	SIGNAL signal_wire10	:  STD_LOGIC;
	SIGNAL signal_wire11	:  STD_LOGIC_VECTOR (2 DOWNTO 0);
	SIGNAL signal_wire12	:  STD_LOGIC_VECTOR (3 DOWNTO 0);
	SIGNAL signal_wire13	:  STD_LOGIC_VECTOR (1 DOWNTO 0);
	SIGNAL signal_wire14	:  STD_LOGIC_VECTOR (2 DOWNTO 0);
	SIGNAL signal_wire15	:  STD_LOGIC_VECTOR (2 DOWNTO 0);
	SIGNAL signal_wire16	:  STD_LOGIC_VECTOR (6 DOWNTO 0);
	SIGNAL signal_wire17	:  STD_LOGIC_VECTOR (1 DOWNTO 0);
	SIGNAL signal_wire18	:  STD_LOGIC_VECTOR (15 DOWNTO 0);
	SIGNAL signal_wire19	:  STD_LOGIC_VECTOR (15 DOWNTO 0);

	COMPONENT ddr_ctl_auk_ddr_sdram
	GENERIC (
		gMEM_TYPE	: STRING;
		gLOCAL_AVALON_IF	: STRING;
		gREG_DIMM	: STRING;
		gPIPELINE_COMMANDS	: STRING;
		gEXTRA_PIPELINE_REGS	: STRING;
		gFAMILY	: STRING;
		gPIPELINE_READDATA	: STRING;
		gUSER_REFRESH	: STRING;
		gADDR_CMD_NEGEDGE	: STRING;
		gINTER_RESYNCH	: STRING;
		gSTRATIX_DLL_CONTROL	: STRING
	);
	PORT (
		resynch_clk	: IN STD_LOGIC;
		addrcmd_clk	: IN STD_LOGIC;
		postamble_clk	: IN STD_LOGIC;
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		write_clk	: IN STD_LOGIC;
		capture_clk	: IN STD_LOGIC;
		local_read_req	: IN STD_LOGIC;
		local_write_req	: IN STD_LOGIC;
		local_addr	: IN STD_LOGIC_VECTOR (22 DOWNTO 0);
		local_wdata	: IN STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_be	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		local_size	: IN STD_LOGIC_VECTOR (0 DOWNTO 0);
		local_burstbegin	: IN STD_LOGIC;
		local_refresh_req	: IN STD_LOGIC;
		local_autopch_req	: IN STD_LOGIC;
		mem_tcl	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		mem_bl	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		mem_odt	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_btype	: IN STD_LOGIC;
		mem_dll_en	: IN STD_LOGIC;
		mem_drv_str	: IN STD_LOGIC;
		mem_trcd	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		mem_tras	: IN STD_LOGIC_VECTOR (3 DOWNTO 0);
		mem_twtr	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_twr	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		mem_trp	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		mem_trfc	: IN STD_LOGIC_VECTOR (6 DOWNTO 0);
		mem_tmrd	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		mem_trefi	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		mem_tinit_time	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		local_ready	: OUT STD_LOGIC;
		local_rdata	: OUT STD_LOGIC_VECTOR (31 DOWNTO 0);
		local_rdata_valid	: OUT STD_LOGIC;
		local_rdvalid_in_n	: OUT STD_LOGIC;
		local_init_done	: OUT STD_LOGIC;
		local_refresh_ack	: OUT STD_LOGIC;
		local_wdata_req	: OUT STD_LOGIC;
		clk_to_sdram	: OUT STD_LOGIC;
		clk_to_sdram_n	: OUT STD_LOGIC;
		ddr_cs_n	: OUT STD_LOGIC;
		ddr_cke	: OUT STD_LOGIC;
		ddr_a	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0);
		ddr_ba	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		ddr_ras_n	: OUT STD_LOGIC;
		ddr_cas_n	: OUT STD_LOGIC;
		ddr_we_n	: OUT STD_LOGIC;
		ddr_dm	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		ddr_dq	: INOUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		ddr_dqs	: INOUT STD_LOGIC_VECTOR (1 DOWNTO 0)
	);

	END COMPONENT;

BEGIN
	signal_wire0  <=  '0';
	signal_wire1  <= (others => '1');
	signal_wire2  <=  '0';
	signal_wire3  <=  '0';
	signal_wire4  <=  '0';
	signal_wire5  <=  B"110";
	signal_wire6  <=  B"001";
	signal_wire7  <=  B"00";
	signal_wire8  <=  '0';
	signal_wire9  <=  '0';
	signal_wire10  <=  '0';
	signal_wire11  <=  B"010";
	signal_wire12  <=  X"5";
	signal_wire13  <=  B"01";
	signal_wire14  <=  B"010";
	signal_wire15  <=  B"010";
	signal_wire16  <=  B"0001000";
	signal_wire17  <=  B"10";
	signal_wire18  <=  X"030b";
	signal_wire19  <=  X"4e1f";

	ddr_ctl_auk_ddr_sdram_inst : ddr_ctl_auk_ddr_sdram
	GENERIC MAP (
		gMEM_TYPE => "ddr_sdram",
		gLOCAL_AVALON_IF => "false",
		gREG_DIMM => "false",
		gPIPELINE_COMMANDS => "true",
		gEXTRA_PIPELINE_REGS => "true",
		gFAMILY => "Cyclone II",
		gPIPELINE_READDATA => "true",
		gUSER_REFRESH => "false",
		gADDR_CMD_NEGEDGE => "true",
		gINTER_RESYNCH => "true",
		gSTRATIX_DLL_CONTROL => "true"
	)
	PORT MAP (
		resynch_clk  =>  clk,
		addrcmd_clk  =>  addrcmd_clk,
		postamble_clk  =>  write_clk,
		clk  =>  clk,
		reset_n  =>  reset_n,
		write_clk  =>  write_clk,
		capture_clk  =>  signal_wire0,
		local_read_req  =>  local_read_req,
		local_write_req  =>  local_write_req,
		local_addr  =>  local_addr,
		local_wdata  =>  local_wdata,
		local_be  =>  local_be,
		local_ready  =>  local_ready,
		local_rdata  =>  local_rdata,
		local_rdata_valid  =>  local_rdata_valid,
		local_rdvalid_in_n  =>  local_rdvalid_in_n,
		local_init_done  =>  local_init_done,
		local_refresh_ack  =>  local_refresh_ack,
		local_wdata_req  =>  local_wdata_req,
		local_size  =>  signal_wire1,
		local_burstbegin  =>  signal_wire2,
		local_refresh_req  =>  signal_wire3,
		local_autopch_req  =>  signal_wire4,
		clk_to_sdram  =>  clk_to_sdram,
		clk_to_sdram_n  =>  clk_to_sdram_n,
		ddr_cs_n  =>  ddr_cs_n,
		ddr_cke  =>  ddr_cke,
		ddr_a  =>  ddr_a,
		ddr_ba  =>  ddr_ba,
		ddr_ras_n  =>  ddr_ras_n,
		ddr_cas_n  =>  ddr_cas_n,
		ddr_we_n  =>  ddr_we_n,
		ddr_dq  =>  ddr_dq,
		ddr_dqs  =>  ddr_dqs,
		ddr_dm  =>  ddr_dm,
		mem_tcl  =>  signal_wire5,
		mem_bl  =>  signal_wire6,
		mem_odt  =>  signal_wire7,
		mem_btype  =>  signal_wire8,
		mem_dll_en  =>  signal_wire9,
		mem_drv_str  =>  signal_wire10,
		mem_trcd  =>  signal_wire11,
		mem_tras  =>  signal_wire12,
		mem_twtr  =>  signal_wire13,
		mem_twr  =>  signal_wire14,
		mem_trp  =>  signal_wire15,
		mem_trfc  =>  signal_wire16,
		mem_tmrd  =>  signal_wire17,
		mem_trefi  =>  signal_wire18,
		mem_tinit_time  =>  signal_wire19
	);


END SYN;


-- =========================================================
-- DDR SDRAM Controller Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, DDR SDRAM Controller Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="DDR SDRAM Controller"  version="13.0"  build="1"  iptb_version="1.3.0 Build 232"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.DDRSDRAMModel"  active_core="ddr_ctl_auk_ddr_sdram" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "use_mem" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "gMEM_TYPE" value="ddr_sdram"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ddio_memory_clocks" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "new_wizard" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_burst_length" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "burst_length" value="2"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "odt_setting" value="Disabled"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "chip_selects_per_dimm" value="1"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "mig_device" value="NONE"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mig_package" value="NONE"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mig_speed_grade" value="NONE"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mig_family" value="NONE"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mig_defaultByteGroups" value="default_value"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mig_ByteGroups" value="default_value"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ADVANCED" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "include_x4_dm_pins" value="1"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "chipselects" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "LOCAL_WIDTH" value="32"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "bankbits" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "width" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "colbits" value="9"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rowbits" value="13"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dq_per_dqs" value="8"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "pch_bit" value="10"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "migratable_bytegroups" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "reg_dimm" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "pipeline_commands" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enable_resynch_clk" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enable_capture_clk" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "obj_hierarchy_path" value="Automatically extracted by Quartus synthesis"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "clock_pin_positive" value="clk_to_sdram[0]"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "clock_pin_negative" value="clk_to_sdram_n[0]"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "clock_fed_back_input" value="fedback_clk_in"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "run_add_constraints" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "run_verify_timing" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "generate_pll" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "update_top_level" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "manual_hierarchy_control" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "fed_back_clock" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "extra_pipeline_regs" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pipeline_readdata" value="Automatic"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "addr_command" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "user_refresh" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "avalon" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "clock_speed" value="100.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "cas_latency" value="2.5"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "burst_type_int" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "burst_type" value="sequential"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "dll_enable" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "drive_strength" value="normal"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ras_to_cas_delay" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "act_pch_time" value="5"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "write_to_read" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "write_recovery_time" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "row_precharge_time" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "refresh_command" value="8"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "load_mode" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "trefi" value="779"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "tinit_time" value="19999"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "trcd" value="15"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "tras" value="42"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "twr" value="15"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "trp" value="15"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "trfc" value="72"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "tmrd" value="12"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "user_trefi" value="7.8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "user_tinit" value="200.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "use_project_timing_estimates" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "device" value="EP2C35"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "package" value="F484"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "speed_grade" value="C8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "top_level" value="ddr_proj"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pin_prefix" value="ddr_"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "family" value="Cyclone II"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "resynch_cycle" value="1"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "intermediate_resynch" value="1"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "resynch_edge" value="falling"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "capture_edge" value="rising"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "resync_phase" value="180"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "fedback_resync_phase" value="0"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "capture_phase" value="-1"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "postamble_phase" value="90"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "stratixii_dqs_phase" value="9999"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "stratixii_dll_delay_buffer_mode" value="undefined"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "stratixii_dll_delay_chain_length" value="99"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "stratixii_dqs_out_mode" value="undefined"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "enable_postamble_logic" value="1"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "stratix_dll_control" value="1"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "manual_pin_control" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "pf_pin_load_on_dq" value="4"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "pf_pin_load_on_cmd" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "pf_pin_load_on_clk" value="2"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "fed_back_clock_delay" value="2000"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "board_tpd_clock_trace_nom" value="500"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_tpd_dqs_trace_total_nom" value="500"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_pcb_delay_var_percent" value="5"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_tskew_data_group" value="20"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tDQSQ" value="450"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tQHS" value="550"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tDQSCK" value="600"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tAC" value="700"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_fmax_at_cl5" value="0.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_fmax_at_cl4" value="0.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_fmax_at_cl3" value="167.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_fmax_at_cl25" value="167.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_fmax_at_cl2" value="134.0"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tCK_MAX" value="13000"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tDS" value="450"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tDH" value="450"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tdqss_min" value="0.75"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_tdqss_max" value="1.25"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "byte_groups" value="4TL 4T"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "override_resynch_script" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "override_capture_script" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "override_postamble_script" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "override_timings" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "postamble_cycle" value="1"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "postamble_edge" value="falling"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "inter_postamble" value="0"  type="BOOLEAN"  enable="0" />
-- Retrieval info:      <PRIVATE name = "postamble_clock" value="write_clk"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "postamble_buffers" value="0"  type="INTEGER"  enable="0" />
-- Retrieval info:      <PRIVATE name = "capture_clk" value="dedicated"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_name" value="0"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "device_maxwidth_name" value="80"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "Default_ByteGroups" value="3T 5T 4T 2T 2R 0R 1R 3R 2B 4B"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "Board_ByteGroups" value="default_value"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "board_maxwidth" value="400"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "memory_device" value="Micron MT46V16M16TG-6T"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "resynch_clk" value="clk"  type="STRING"  enable="0" />
-- Retrieval info:      <PRIVATE name = "pin_file" value="none"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_address_width" value="23"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "local_data_width" value="32"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "clock_pairs" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "alterppf">
-- Retrieval info:      <PRIVATE name = "specify_username" value="1"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "greybox">
-- Retrieval info:      <PRIVATE name = "disable_cut_checks" value="1"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filename" value="ddr_ctl_syn.v"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "qip">
-- Retrieval info:      <PRIVATE name = "gx_libs" value="1"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="VHDL"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "nativelink_includes" value="ddr_ctl_auk_ddr_datapath_pack.vhd"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "filename" value="ddr_ctl.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "WEB_BROWSER" value="/usr/bin/firefox"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "LICENSE_FILE" value="/home/ax/altera/Lizenz/license_90.dat"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP2C35F484C8"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone II"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS/>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
